USE northwind;
DROP TABLE IF EXISTS trantest;
CREATE TABLE trantest(campo INT NOT NULL PRIMARY KEY, descripcion VARCHAR(50)) ENGINE = InnoDB;
INSERT INTO trantest VALUES(1,"Primer registro"),(2,"Segundo registro"),(3,"Tercer registro");
START TRANSACTION;
INSERT INTO trantest VALUES(4,"Cuarto registro"),(5,"Quinto registro");
ROLLBACK;
SAVEPOINT S1;
INSERT INTO trantest VALUES(6,"Sexto registro"),(7,"Septimo registro");
ROLLBACK TO S1;
START TRANSACTION;
INSERT INTO trantest VALUES(6,"Sexto registro"),(7,"Septimo registro");
COMMIT;